# Generated by Django 3.2.8 on 2021-10-13 01:54

from django.db import migrations

ProductStatuses = {
    0: ('Draft', False),
    1: ('Published', True),
    2: ('Discontinued', False)
}

def insert_initial_product_statuses(apps, schema_editor):
    ProductStatus = apps.get_model('store', 'ProductStatus')
    for id, data in ProductStatuses.items():
        ProductStatus.objects.create(id=id, name=data[0], show_in_catalog=data[1])

def destroy_initial_product_statuses(apps, schema_editor):
    ProductStatus = apps.get_model('store', 'ProductStatus')
    ProductStatus.objects.filter(id__in=ProductStatuses.keys()).delete()

class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(insert_initial_product_statuses, destroy_initial_product_statuses)
    ]
