# Generated by Django 3.2.8 on 2021-10-14 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_siteconfig'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteconfig',
            name='tagline',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
